### ISSUE TITLE
Separate data by country

### ISSUE THREAD

**Issue by gsilvapt** [okfn-oe/Econ-Factbook#5]
With Pull #4, the goal is to split data by country and, later, by year.

Next, using the [datapackage-validator](https://github.com/okfn-oe/datapackage-validator), we create the different datasets and have them in the project's repository.

**Comment by mcallaghan** [comment]
Not sure what you mean. By country is each row of the dataset, by year is each column (tab separated). Or do you want a separate file for population in each year and each country?

If you want json eventually, if that's what I understand from the linked repo, I would suggest getting data directly from the API.

Depending on how you want to use the data anyway, this might be more sensible. You don't need to download all the data onto your server so that you can print it back to website users if you can get it straight from WB as the user requests it.

Maybe it would help to get clear how you want to use the data in the end and work back from there?

**Comment by gsilvapt** [comment]
The idea is to make data accessible. On the other hand, I'm not 100% sure how this should be posted online. In fact, creating a dataset per country is not useful, specially when it will use loads of space and it is not practical to do analysis. Perhaps we should keep it this way.

I just want to post the data online, using Open Data's standards.

**Comment by gsilvapt** [comment]
Okay, so I finally have beaten Python and APIs. Just sharing my achievement with commit https://github.com/okfn-oe/Econ-Factbook/commit/8a864426497da8449c75c70801a92479e5897d60 .

So, the Python script, using a few dedicated Python Packages, now fetches the data and saves it into a csv file. 
We now have data of the numbers of the Population from 1960 to 2014.
Next step is to split the data into the many sources @mcnabber091 used.

Closing this issue and opening #9 for further improvements of the Python script.
